openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost
  description: Generated server url
paths:
  /user/{id}:
    get:
      tags:
      - user-controller
      operationId: getUser
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UserDetails'
components:
  schemas:
    UserDetails:
      type: object
      properties:
        username:
          type: string
